"""Derive case answer keys by executing reference SQL against the frozen corpus.

Answer keys are never hand-asserted. A key written by hand can silently
disagree with the data it describes, and by E1b both are frozen together and
the disagreement becomes permanent.

Keys are written to a file separate from the cases so that the authored prompt
and the correct answer are not the same object — the harness surfaces prompts
to the agent and must never be one field access away from the key.

Run: uv run --with pyyaml python freeze/derive_answer_keys.py
"""

from __future__ import annotations

import sqlite3
import sys
from decimal import Decimal
from pathlib import Path
from typing import Any

import yaml

ROOT = Path(__file__).resolve().parent.parent
SPLITS = ("calibration", "evaluation")
WORKLOAD = "data-sql"


def build_corpus(corpus_ref: str) -> sqlite3.Connection:
    corpus = ROOT / corpus_ref
    db = sqlite3.connect(":memory:")
    db.executescript((corpus / "schema.sql").read_text(encoding="utf-8"))
    db.executescript((corpus / "seed.sql").read_text(encoding="utf-8"))
    violations = db.execute("PRAGMA foreign_key_check").fetchall()
    if violations:
        raise SystemExit(f"corpus {corpus_ref} has foreign-key violations: {violations}")
    return db


def scalar(db: sqlite3.Connection, sql: str) -> Any:
    rows = db.execute(sql).fetchall()
    if len(rows) != 1 or len(rows[0]) != 1:
        raise SystemExit(f"reference SQL must return exactly one scalar:\n{sql}")
    return rows[0][0]


def derive(case: dict[str, Any], db: sqlite3.Connection) -> dict[str, Any]:
    case_id = case["case_id"]

    if case["expected_outcome"] == "partial":
        if "reference" in case:
            raise SystemExit(f"{case_id}: unanswerable case must not carry reference SQL")
        return {
            "expected_outcome": "partial",
            "unmet_criteria": case["unmet_criteria"],
        }

    ref = case["reference"]
    raw = scalar(db, ref["value_sql"])
    if raw is None:
        raise SystemExit(f"{case_id}: reference value SQL returned NULL — the case is unanswerable")
    rows = scalar(db, ref["rows_sql"])
    if not rows:
        raise SystemExit(f"{case_id}: reference row SQL returned zero contributing rows")

    key: dict[str, Any] = {"expected_outcome": "answer", "units": case["units"]}
    if ref["value_is_cents"]:
        cents = int(raw)
        key["result_value"] = float(Decimal(cents) / 100)
        key["result_value_cents"] = cents
    else:
        key["result_value"] = int(raw)
    key["row_count"] = int(rows)
    return key


def main() -> int:
    for split in SPLITS:
        source = ROOT / "cases" / split / WORKLOAD / "cases.yaml"
        doc = yaml.safe_load(source.read_text(encoding="utf-8"))
        db = build_corpus(doc["corpus_ref"])

        keys = {case["case_id"]: derive(case, db) for case in doc["cases"]}
        if len(keys) != len(doc["cases"]):
            raise SystemExit(f"{split}: duplicate case_id")

        target = source.with_name("answer-keys.yaml")
        header = (
            "# GENERATED by freeze/derive_answer_keys.py — do not hand-edit.\n"
            "# Every value here was computed by executing the case's reference SQL\n"
            f"# against {doc['corpus_ref']}. Regenerate rather than correct.\n"
            f"# Split: {split}. Workload: {WORKLOAD}.\n\n"
        )
        target.write_text(
            header + yaml.safe_dump(keys, sort_keys=True, allow_unicode=True),
            encoding="utf-8",
            newline="\n",
        )
        print(f"{split}: {len(keys)} keys -> {target.relative_to(ROOT).as_posix()}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
